version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: database_inventory_control
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=inventory
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: inventory_control
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local
